- name: copy kubeadm join config
  become: yes
  template:
    src: kubeadm-join.yaml
    dest: /etc/kubeadm-join.yaml

- name: running kubeadm join
  become: yes
  command: kubeadm join {{ networking.controlPlaneEndpoint }} --node-name {{ inventory_hostname }} --token {{ token }}  --discovery-token-ca-cert-hash {{ cert_hash }}
