- name: install Tigera Calico operator
  become: yes
  command: kubectl --kubeconfig=/etc/kubernetes/admin.conf create -f https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/tigera-operator.yaml


- name: copy custom-resources config
  become: yes
  template:
    src: custom-resources.yaml
    dest: /etc/custom-resources.yaml

- name: install Calico
  become: yes
  command: kubectl --kubeconfig=/etc/kubernetes/admin.conf create -f /etc/custom-resources.yaml

