# Link to API docs: https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2

apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
nodeRegistration:
  criSocket: "unix:///run/containerd/containerd.sock"
discovery:
  bootstrapToken:
    apiServerEndpoint: "{{ networking.controlPlaneEndpoint }}"
    token: "{{ token }}"
    caCertHashes:
      - "{{ cert_hash }}"
